DROP TABLE "auction_bids" CASCADE;--> statement-breakpoint
DROP TABLE "auction_truck_types" CASCADE;--> statement-breakpoint
DROP TABLE "auctions" CASCADE;--> statement-breakpoint
DROP TABLE "available_trucks" CASCADE;--> statement-breakpoint
DROP TABLE "border_crossings" CASCADE;--> statement-breakpoint
DROP TABLE "cities" CASCADE;--> statement-breakpoint
DROP TABLE "classified_images" CASCADE;--> statement-breakpoint
DROP TABLE "cmr_signatures" CASCADE;--> statement-breakpoint
DROP TABLE "company_badges" CASCADE;--> statement-breakpoint
DROP TABLE "company_blacklist" CASCADE;--> statement-breakpoint
DROP TABLE "company_favorites" CASCADE;--> statement-breakpoint
DROP TABLE "conversation_participants" CASCADE;--> statement-breakpoint
DROP TABLE "conversations" CASCADE;--> statement-breakpoint
DROP TABLE "dossier_documents" CASCADE;--> statement-breakpoint
DROP TABLE "dossier_events" CASCADE;--> statement-breakpoint
DROP TABLE "driver_certificates" CASCADE;--> statement-breakpoint
DROP TABLE "driver_hours" CASCADE;--> statement-breakpoint
DROP TABLE "e_cmr_consignments" CASCADE;--> statement-breakpoint
DROP TABLE "e_cmr_events" CASCADE;--> statement-breakpoint
DROP TABLE "e_cmr_signatures" CASCADE;--> statement-breakpoint
DROP TABLE "entity_views" CASCADE;--> statement-breakpoint
DROP TABLE "factoring_requests" CASCADE;--> statement-breakpoint
DROP TABLE "flagged_contacts" CASCADE;--> statement-breakpoint
DROP TABLE "forum_replies" CASCADE;--> statement-breakpoint
DROP TABLE "forum_threads" CASCADE;--> statement-breakpoint
DROP TABLE "freight_bids" CASCADE;--> statement-breakpoint
DROP TABLE "freight_documents" CASCADE;--> statement-breakpoint
DROP TABLE "freight_equipment" CASCADE;--> statement-breakpoint
DROP TABLE "freight_favorites" CASCADE;--> statement-breakpoint
DROP TABLE "freight_truck_types" CASCADE;--> statement-breakpoint
DROP TABLE "incident_replies" CASCADE;--> statement-breakpoint
DROP TABLE "info_articles" CASCADE;--> statement-breakpoint
DROP TABLE "invoice_guarantees" CASCADE;--> statement-breakpoint
DROP TABLE "marketplace_clicks" CASCADE;--> statement-breakpoint
DROP TABLE "messages" CASCADE;--> statement-breakpoint
DROP TABLE "order_documents" CASCADE;--> statement-breakpoint
DROP TABLE "order_positions" CASCADE;--> statement-breakpoint
DROP TABLE "order_stops" CASCADE;--> statement-breakpoint
DROP TABLE "order_tracking_shares" CASCADE;--> statement-breakpoint
DROP TABLE "public_tracking_tokens" CASCADE;--> statement-breakpoint
DROP TABLE "route_alerts" CASCADE;--> statement-breakpoint
DROP TABLE "saved_routes" CASCADE;--> statement-breakpoint
DROP TABLE "tachograph_files" CASCADE;--> statement-breakpoint
DROP TABLE "transport_dossiers" CASCADE;--> statement-breakpoint
DROP TABLE "truck_documents" CASCADE;--> statement-breakpoint
DROP TABLE "truck_favorites" CASCADE;--> statement-breakpoint
DROP TABLE "truck_positions" CASCADE;